spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/snipxn?stringtype=unspecified
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 3000ms

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  mail:
    host: smtp.resend.com
    port: 465
    username: resend
    password: ${MAIL_API_KEY:${MAIL_API_KEY}}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

# 开发环境打印 SQL 日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

snipxn:
  jwt:
    secret: ${JWT_SECRET:${JWT_SECRET}}
  mail:
    from: noreply@zanolab.com
  sandbox:
    judge0-url: ${JUDGE0_URL:http://192.168.241.130:2358}
    judge0-api-key: ${JUDGE0_API_KEY:}
  oauth:
    github:
      client-id: ${GITHUB_CLIENT_ID:${GITHUB_CLIENT_ID}}
      client-secret: ${GITHUB_CLIENT_SECRET:${GITHUB_CLIENT_SECRET}}
    google:
      client-id: ${GOOGLE_CLIENT_ID:${GOOGLE_CLIENT_ID}}
      client-secret: ${GOOGLE_CLIENT_SECRET:${GOOGLE_CLIENT_SECRET}}
  ai:
    deepseek-url: ${DEEPSEEK_URL:https://api.deepseek.com}
    api-key: ${DEEPSEEK_API_KEY:${DEEPSEEK_API_KEY}}

logging:
  level:
    com.snipxn: debug
