-- 用户个人资料扩展字段
ALTER TABLE users ADD COLUMN IF NOT EXISTS website    VARCHAR(255);
ALTER TABLE users ADD COLUMN IF NOT EXISTS github     VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS location   VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS company    VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS tech_stack VARCHAR(500);
